// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjNxycEwF1jqptX0zdkja3u40VCVYjGU',
    appId: '1:886774767078:web:b4efc4df8017909a768a27',
    messagingSenderId: '886774767078',
    projectId: 'easy-first-aid-e3f8f',
    authDomain: 'easy-first-aid-e3f8f.firebaseapp.com',
    storageBucket: 'easy-first-aid-e3f8f.appspot.com',
    measurementId: 'G-9GF66R0Z4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjdVXGes1tTvMDHZD6Yzgm_0mKl5lwtto',
    appId: '1:886774767078:android:c06fb34ca1d944a1768a27',
    messagingSenderId: '886774767078',
    projectId: 'easy-first-aid-e3f8f',
    storageBucket: 'easy-first-aid-e3f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_0P_BzAHetyqMPc8umWqPh6GRw1lzhis',
    appId: '1:886774767078:ios:387c8817790a6d20768a27',
    messagingSenderId: '886774767078',
    projectId: 'easy-first-aid-e3f8f',
    storageBucket: 'easy-first-aid-e3f8f.appspot.com',
    iosBundleId: 'com.example.easyFirstAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_0P_BzAHetyqMPc8umWqPh6GRw1lzhis',
    appId: '1:886774767078:ios:387c8817790a6d20768a27',
    messagingSenderId: '886774767078',
    projectId: 'easy-first-aid-e3f8f',
    storageBucket: 'easy-first-aid-e3f8f.appspot.com',
    iosBundleId: 'com.example.easyFirstAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdjNxycEwF1jqptX0zdkja3u40VCVYjGU',
    appId: '1:886774767078:web:ab724a5862412880768a27',
    messagingSenderId: '886774767078',
    projectId: 'easy-first-aid-e3f8f',
    authDomain: 'easy-first-aid-e3f8f.firebaseapp.com',
    storageBucket: 'easy-first-aid-e3f8f.appspot.com',
    measurementId: 'G-EHW8MPNFBK',
  );
}